local m, s, o
local sys = require "luci.sys"

m = Map("mentohust", translate("MentoHUST 设置"), 
    translate("配置 802.1x 认证参数。保存配置后服务将自动重启。"))

s = m:section(NamedSection, "default", "mentohust", translate("基本设置"))
s.anonymous = true
s.addremove = false

-- 启用服务选项
o = s:option(Flag, "enabled", translate("启用服务"))
o.rmempty = false

o = s:option(Value, "username", translate("用户名"))
o.rmempty = false

o = s:option(Value, "password", translate("密码"))
o.password = true
o.rmempty = false

o = s:option(Value, "nic", translate("认证网卡"))
for _, dev in ipairs(luci.sys.net.devices()) do
    if dev ~= "lo" then o:value(dev) end
end
o.default = "eth0"
o.rmempty = false

s = m:section(NamedSection, "default", "mentohust", translate("高级设置"))
s.anonymous = true
s.addremove = false

o = s:option(Value, "ip", translate("IP地址"))
o.default = "0.0.0.0"
o.description = translate("DHCP用户请保留 0.0.0.0")

o = s:option(Value, "mask", translate("子网掩码"))
o.default = "0.0.0.0"
o.description = translate("掩码，无关紧要")

o = s:option(Value, "gateway", translate("网关"))
o.default = "0.0.0.0"
o.description = translate("网关，如果指定了就会监视网关ARP信息")

o = s:option(Value, "dns", translate("DNS服务器"))
o.default = "0.0.0.0"
o.description = translate("DNS服务器，无关紧要")

o = s:option(ListValue, "startmode", translate("组播模式"))
o:value("0", translate("标准"))
o:value("1", translate("锐捷"))
o:value("2", translate("赛尔"))
o.default = "0"
o.description = translate("寻找服务器时的组播地址类型 0标准 1锐捷 2将MentoHUST用于赛尔认证")

o = s:option(ListValue, "dhcpmode", translate("DHCP方式"))
o:value("0", translate("不使用"))
o:value("1", translate("二次认证"))
o:value("2", translate("认证后"))
o:value("3", translate("认证前"))
o.default = "1"
o.description = translate("DHCP方式 0(不使用) 1(二次认证) 2(认证后) 3(认证前)")

o = s:option(Value, "pinghost", translate("Ping主机"))
o.default = "0.0.0.0"
o.description = translate("Ping主机，用于掉线检测，0.0.0.0表示关闭该功能")

o = s:option(Value, "timeout", translate("超时时间(秒)"))
o.default = "8"
o.description = translate("每次发包超时时间（秒）")

o = s:option(Value, "echointerval", translate("心跳间隔(秒)"))
o.default = "30"
o.description = translate("发送Echo包的间隔（秒）")

o = s:option(Value, "restartwait", translate("失败等待(秒)"))
o.default = "15"
o.description = translate("失败等待（秒）认证失败后等待RestartWait秒或者服务器请求后重启认证")

o = s:option(Value, "version", translate("客户端版本"))
o.default = "0.00"
o.description = translate("客户端版本号，如果未开启客户端校验但对版本号有要求，可以在此指定，形如3.30")

o = s:option(Value, "dhcpscript", translate("DHCP脚本命令"))
o.default = "udhcpc -i eth0 -q"
o.description = translate("指定执行 DHCP 的命令。其中的网卡接口请与上方的 '认证网卡' 保持一致。")
o.rmempty = false


m.on_after_commit = function(self)
    local uci = require("luci.model.uci").cursor()
    local username = uci:get("mentohust", "default", "username")
    if not username or username == "" then return end

    local mappings = {
        { "username",     "Username",     "用户名" },
        { "password",     "Password",     "明文密码" },
        { "nic",          "Nic",          "网卡" },
        { "ip",           "IP",           "IP地址" },
        { "mask",         "Mask",         "子网掩码" },
        { "gateway",      "Gateway",      "网关" },
        { "dns",          "DNS",          "DNS服务器" },
        { "pinghost",     "PingHost",     "Ping主机" },
        { "timeout",      "Timeout",      "超时时间" },
        { "echointerval", "EchoInterval", "心跳间隔" },
        { "restartwait",  "RestartWait",  "失败等待" },
        { "startmode",    "StartMode",    "组播模式" },
        { "dhcpmode",     "DhcpMode",     "DHCP方式" },
        { "version",      "Version",      "客户端版本" },
        { "dhcpscript",   "DhcpScript",   "DHCP脚本" }
    }

    local content = {}
    table.insert(content, "# MentoHUST Configuration Generated by LuCI")
    table.insert(content, "[MentoHUST]")
    table.insert(content, "MaxFail=0")
    
    for _, map in ipairs(mappings) do
        local uci_key = map[1]
        local conf_key = map[2]
        local comment = map[3]
        local val = uci:get("mentohust", "default", uci_key) or ""
        
        table.insert(content, ";" .. comment)
        table.insert(content, conf_key .. "=" .. val)
    end
    
    table.insert(content, "EncodePass=") 
    table.insert(content, "DaemonMode=0")
    table.insert(content, "ShowNotify=0")
    table.insert(content, "DataFile=/etc/mentohust/")

    local f = io.open("/etc/mentohust.conf", "w")
    if f then
        f:write(table.concat(content, "\n") .. "\n")
        f:close()
    end

    local enabled = uci:get("mentohust", "default", "enabled")
    if enabled == "1" then
        sys.call("/etc/init.d/mentohust restart >/dev/null 2>&1")
    else
        sys.call("/etc/init.d/mentohust stop >/dev/null 2>&1")
    end
end

return m